### PR TITLE
Nadav from JFrog. Banner for conan days.

### PR DESCRIPTION
**Pull request by ncamaa**

### CODE REVIEW

**Comment by danimtb** [comment]
Hi Nadav!

It seems that you have included the autogenerated jekyll files in this PR as well. I think the valid files should be the images and the changes you have done in the css and index.html. Would you mind checking it please?

**Comment by danimtb** [comment]
Hi nadav! I am having a look at your changes and this is how the blog looks like with your changes:

image

Shouldn't the banner be at the top of the page?

**Comment by ncamaa** [comment]
Yes, Daniel, you are correct. It is all confirmed by our design team.  On mobile, the banner will be after the 1st post.

**Comment by memsharded** [comment]
Actually, the banner in the "table of contents" of the blog post was not the goal, but having the banner in the left column of the posts, because there is where the visits are.

Please contribute the banner to the posts view, not to the table of contents. Thanks!

**Pull request merged**
