### PR TITLE
Add search bar

### LINKED ISSUE #96: [suggestion] Add search bar
Hi!

The blog contains cool explanation about many features, but sometimes it's hard to find a specific topic that I read in the past and I want to read again. It would be nice to add search bar, just like in docs.conan.io.

### PR DESCRIPTION
**Pull request by uilianries**
Added a search which uses Google search engine to find a keyword.
I would prefer something on client side, like lunr, but my web skills are limited.

closes #96 

preview:

Screenshot_2019-10-22 Screenshot

Type "CMake" and Search:

Screenshot_2019-10-22 Screenshot(1)

### CODE REVIEW

**Comment by danimtb** [comment]
Can we make the search button color match the header one? Have you tried how it looks from mobile?

**Comment by uilianries** [comment]
> Can we make the search button color match the header one?

Yes. I'll do it.

> Have you tried how it looks from mobile?

Nope. Good test, lemme check it.

**Comment by uilianries** [comment]
Mobile preview using Conan color for search button:

Screenshot_2019-10-23-10-57-07-418_com android chrome

Search for "CMake":

Screenshot_2019-10-23-10-57-59-786_com android chrome

**Comment by uilianries** [comment]
I don't like to see the search bar duplicated on search page. I would need to created a new template to fix it. WDYT @danimtb ?

**Comment by uilianries** [comment]
Okay, I just removed the search bar from the search page. It looks better now.

**Desktop** 


Screenshot_2019-10-23 Screenshot(1)
Screenshot_2019-10-23 Conan 1 19 Better integration for CMake and Pkg-Config, OSX frameworks support, enabling and disablin
Screenshot_2019-10-23 Screenshot

**Mobile**
Screenshot_2019-10-23-14-20-03-777_com android chrome
Screenshot_2019-10-23-14-21-05-064_com android chrome
Screenshot_2019-10-23-14-21-28-580_com android chrome

**Comment by czoido** [comment]
Tested on Linux, Mac, Windows with major browsers and mobile.

**Pull request merged**
